export const subSections = {
  Tech: {
    Apple: ["iPhone", "MacBook", "iPad"],
    Audio: ["Headphones", "Speakers", "Earbuds"],
    Cameras: ["DSLR", "Mirrorless", "Action-Cameras"],
    Computers: ["Laptops", "Desktops", "Tablets"],
    Smartphones: ["Android", "iOS", "Windows-Phone"],
    TVs: ["LG", "Samsung", "Sony", "Projectors"],
  },
  Fashion: {
    "Men's-Fashion-Advice": ["Formal", "Casual", "Business-Casual"],
    "Men's-Fashion-Trends": ["Seasonal-Trends", "Streetwear", "Minimalist"],
    "Men's-Fragrances": ["Cologne", "Perfume", "Body-Spray"],
    "Men's-Hairstyles": ["Short", "Medium", "Long"],
    "Sneakers-&-Shoes": ["Sneakers", "Dress-Shoes", "Boots"],
    Watches: ["Analog", "Digital", "Smartwatches"],
  },
  Rides: {
    Boats: ["Yachts", "Superyachts", "Sailing", "Jetskis", "Submarines"],
    Cars: [
      "Most-Popular-Car-Brands",
      "Electric-Vehicles",
      "SUVs",
      "Porsche",
      "Ford",
      "BMW",
      "Sports-Cars",
      "Mercedes-Benz",
      "Luxury",
      "Reviews",
    ],
    Cycling: [
      "Bicycles",
      "Electric-Bikes",
      "Helmets",
      "Mountain-Bikes",
      "Kickstarter",
      "Buyers-Guides",
      "Best-Electric-Bikes",
    ],
    Flying: [
      "Planes",
      "Jets",
      "Electric-Vehicles",
      "Space",
      "Travel",
      "Auctions",
    ],
    Motorcycles: [
      "Best-Cafe-Racers",
      "Fastest-Motorcycles-in-the-World",
      "Electric-Motorcycles",
      "Harley-Davidson",
      "Cafe-Racers",
      "Triumph",
      "Vintage-Helmets",
      "Motorcycle-Backpacks",
    ],
  },
  Lifestyle: {
    Advice: [
      "Health",
      "Mental-Health",
      "COVID-19",
      "Money",
      "Australia",
      "Work",
      "Productivity",
      "Investing",
      "Cryptocurrency",
    ],
    Drinks: ["Whisky", "Beer", "Wine", "Cocktails", "Bars"],
    Fitness: [
      "Workouts",
      "Shoulder-Exercises",
      "Bicep-Exercises",
      "Triceps-Workouts",
      "Chest-Workouts",
      "Forearm-Workouts",
      "Strongest-Celebrities-in-Hollywood",
      "How-to-Lose-Weight-Fast",
      "Celebrity-Diet-&-Workout-Plans",
      "Gyms",
      "Diet-&-Nutrition",
    ],
    Finance: [
      "Money",
      "Cryptocurrency",
      "Investing",
      "NFTs",
      "Australia",
      "Celebrities",
      "Elon-Musk",
      "Net-Worths",
      "Rich-Lists",
    ],
    Food: [
      "Monday-Munchies",
      "Restaurants",
      "Fast-Food",
      "Sydney",
      "Melbourne",
      "Brisbane",
    ],
    Grooming: [
      "Skincare",
      "Razors",
      "Hair",
      "Beards",
      "Best-Beard-Oils",
      "Best-Body-Groomers",
      "Best-Face-Washes",
      "Men's-Skincare-Guide",
      "Best-Skincare-Products",
      "Beard-Care-Guide",
    ],
    "Sex-&-Dating": [
      "Best-Sex-Toys",
      "Best-Tinder-Bios-for-Guys",
      "How-To-Be-Sexually-Dominant",
      "A-Guide-to-(Safe)-Rough-Sex",
      "How-to-Get-a-Sugar-Momma",
      "Tinder-Pick-Up-Lines-for-Guys",
      "Best-Sex-Positions",
      "Best-Dating-Apps",
    ],
    Travel: [
      "Hotels",
      "Sydney",
      "Melbourne",
      "Best-Hotels-in-the-World",
      "Travel-Gifts",
      "World's-Best-Rooftop-Bars",
      "Skyscanner-Alternatives",
      "Qantas",
    ],
  },
  Entertainment: {
    Art: ["NFTs", "Auctions", "Tattoos", "Collections", "Memes"],
    Books: [
      "Coffee-Table-Books",
      "Self-Help-Books",
      "Cookbooks",
      "Best-Kindles",
    ],
    Gaming: [
      "Top-New-Games",
      "Playstation",
      "Xbox",
      "PC",
      "Nintendo-Switch",
      "LEGO",
      "Sony",
      "Reviews",
    ],
    "Movies-&-TV": [
      "Guide-to-Streaming-Services",
      "New-on-Netflix",
      "New-on-Prime-Video",
      "New-on-Disney+",
      "New-on-Stan-Australia",
      "Best-Action-Movies",
      "Best-Sci-Fi-Movies",
      "Trailers",
      "Netflix",
      "Best-Movies-on-Netflix",
      "Best-Amazon-Prime-Movies",
      "Best-Shows-on-Netflix",
      "Documentaries",
      "James-Bond",
    ],
    Music: ["Guitars", "Festivals", "Hip-Hop"],
    Sport: [
      "Golf",
      "NBA",
      "Football",
      "Boxing",
      "Tennis",
      "UFC",
      "AFL",
      "Formula-1",
    ],
  },
  Living: {
    Appliances: [
      "Vacuum-Cleaners",
      "Coffee",
      "Kitchens",
      "Cooking",
      "Lighting",
      "Dyson",
      "Best-Coffee-Machines",
      "Best-Air-Fryers",
      "Best-Robot-Vacuums",
    ],
    Architecture: [
      "Homes",
      "Design",
      "Real-Estate",
      "Interior-Design",
      "Penthouses",
      "Celebrity-Homes",
    ],
    Furniture: [
      "Desks",
      "IKEA",
      "Interior-Design",
      "Homes",
      "Italian",
      "Chairs",
      "Office",
      "Tables",
      "Design",
      "Herman-Miller",
    ],
    Homewares: [
      "Decor",
      "Kitchenware",
      "Bedding",
      "Lighting",
      "Storage",
      "Candles",
      "Plants",
      "Art",
    ],
  },
  Outdoors: {
    Camping: [
      "Tents",
      "Campervans",
      "Knives",
      "Vehicles",
      "Australia",
      "4WD",
      "Fishing",
      "Kayaks",
      "Kickstarter",
    ],
    Snow: [
      "Skiing",
      "Snowboarding",
      "Cabins",
      "Best-Ski-Jackets",
      "Best-Snow-Goggles",
      "Best-Ski-Fields-in-New-Zealand",
      "Winter-Must-Haves",
      "Best-Australian-Ski-Fields",
    ],
    Surfing: [
      "Beaches",
      "Wetsuits",
      "Surfboards",
      "Best-Wetsuit-Tops",
      "Best-Wetsuits-for-Surfing",
    ],
    Skate: [
      "Skateboards",
      "Longboards",
      "Protective-Gear",
      "Skate-Shoes",
      "Street-Skating",
    ],
    Hiking: [
      "Trails",
      "Gear",
      "Footwear",
      "Backpacks",
      "Clothing",
      "Best-Hiking-Trails",
      "Camping",
    ],
  },
  News: {
    "World-News": ["Politics", "Economy", "Global-Events", "Climate-Change"],
    "Tech-News": ["AI", "Gadgets", "Startups", "Innovations"],
    "Sports-News": ["Football", "Basketball", "Olympics", "Cricket"],
    "Entertainment-News": ["Movies", "Music", "Celebrities", "TV-Shows"],
  },
};
